const UPDATE_CURRENT = 'UPDATE_CURRENT'
const PREP_CAPTURE = 'PREP_CAPTURE'
const UPDATE_OUTPUT_SHAPE = 'UPDATE_OUTPUT_SHAPE'

module.exports = {
    UPDATE_CURRENT,
    PREP_CAPTURE,
    UPDATE_OUTPUT_SHAPE,
}
