const UPDATE_FRAME = 'UPDATE_FRAME'
const PREP_CAPTURE = 'PREP_CAPTURE'
const UPDATE_OUTPUT_SHAPE = 'UPDATE_OUTPUT_SHAPE'

module.exports = {
    UPDATE_FRAME,
    PREP_CAPTURE,
    UPDATE_OUTPUT_SHAPE,
}
